### ISSUE TITLE
[BUG] There is no document regarding Cross cluster Replication metadata store part.

### ISSUE THREAD

**Issue by chaitrahegde115** [opensearch-project/cross-cluster-replication#1033]
**What is the bug?**
This is raised from https://forum.opensearch.org/t/query-on-cross-cluster-replication-metadata-store/14843 where there is no document available which clearly explains where and how the cross cluster metadata is stored.

**Comment by skumarp7** [comment]
Hi, 

Can I contribute for this? This would be my first contribution. 

Thanks, 
Sanjay K

**Comment by monusingh-1** [comment]
Yes @skumarp7, feel free to contribute.

**Comment by chaitrahegde115** [comment]
Looks like this has been fixed
