### ISSUE TITLE
Cross replicate internal users and roles database

### ISSUE THREAD

**Issue by petro2050** [opensearch-project/cross-cluster-replication#1076]
**Is your feature request related to a problem? Please describe.**
I'm doing a multi-region AWS setup where each region has an OpenSearch cluster. I enabled cross-region replication so only one region acts as the leader. The problem is I don't see a way to replicate internal users, which forces me to define them manually through the security plugin. I'd also like to periodically rotate user passwords (for example with a lambda-based secret rotation). This means the lambda has to issue a PUT request to each and every cluster. This work seems unnecessarily complex and error-prone.

**Describe the solution you'd like**
We should be able to cross-replicate the internal users and roles database across clusters.

**Comment by peternied** [comment]
[Security Triage] This feels out of scope for the security plugin, while there might be features / asks to support cross cluster scenarios, the security plugin is focused on administration of a single OpenSearch instance, transferring this to cross cluster repo where there might be better traction.

**Comment by zalseryani** [comment]
Any update on this ?

**Comment by ankitkala** [comment]
This is not planned as of now as it requires significant changes.

**Comment by cwperks** [comment]
Re-opening to re-visit this feature request.

**Comment by andrross** [comment]
> Re-opening to re-visit this feature request.

To be clear, we do want to solve this problem as a subset of full cluster replication. As @ankitkala called out, replicating users and roles within the current CCR architecture has a lot of edge cases that go away if you're doing full cluster replication.
