### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/cross-cluster-replication#116]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by saikaranam-amazon** [comment]
Pushed changes on main branch
