### ISSUE TITLE
[ACTION NEEDED] Fix flaky integration tests at distribution level 

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/cross-cluster-replication#1362]
**What is the bug?**
It was observed in 2.13.0 and previous other releases that this component manually signed off on the release for failing integration tests. See https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2026436873
The flakiness of the test runs take a lot of time from the release team to collect go/no-go decision and significantly lower the confidence in the release bundles.

**How can one reproduce the bug?**
1. Run integration testing for altering and see the failures. 
2. Issues can be reproduced using the steps declared in AUTOCUT issues for failed integration testing

**What is the expected behavior?**
Tests should be consistently passing.

**Do you have any additional context?**
Please note that this is a hard blocker for 2.14.0 release as per the discussion [here](https://github.com/opensearch-project/opensearch-build/issues/4588)

**Comment by ankitkala** [comment]
Related issue: https://github.com/opensearch-project/opensearch-build/issues/4610

**Comment by gaiksaya** [comment]
Adding 2.14.0 release manager @rishabh6788

**Comment by dblock** [comment]
In 2.15 we ran with automation end-to-end, closing.

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/dbwiddis) [3](https://github.com/krisfreedain) [4](https://github.com/akolarkunnu) [5](https://github.com/mingshl) [6](https://github.com/getsaurabh02)
