### ISSUE TITLE
[BUG] Failed to build plugin on es7.10 branch

### ISSUE THREAD

**Issue by Warkeeper** [opensearch-project/cross-cluster-replication#1413]
**What is the bug?**
Failed to build plugin on es7.10 branch

**How can one reproduce the bug?**
1. pull the ES7.10 branch of the CCR plugin 
2. build it using the command “.\gradlew.bat -x test -x integTest clean build.”

**What is the expected behavior?**
Build successfully.

**What is your host/environment?**
Gradle Version        : 6.8.3
  OS Info               : Windows 10 10.0 (amd64)
  JDK Version           : 15 (Zulu JDK)
  JAVA_HOME             : C:\Users\yangb\.jdks\azul-15.0.9
  Random Testing Seed   : D51FEAC79CEBF6B3
  In FIPS 140 mode      : false

**Do you have any screenshots?**
![image](https://github.com/user-attachments/assets/5ca5ccbb-0bda-4e18-a134-7a34d734b580)

**Do you have any additional context?**
```
> Task :compileKotlin FAILED
e: C:\Codes\ccr-latest\cross-cluster-replication\src\main\kotlin\com\amazon\elasticsearch\replication\seqno\RemoteClusterTranslogService.kt: (29, 112): Too many arguments for public open fun getHistoryOperations(p0: String!, p1: Engine.HistorySource!, p2: Long): Translog.Snapshot! defined in org.elasticsearch.index.shard.IndexShard
e: C:\Codes\ccr-latest\cross-cluster-replication\src\main\kotlin\com\amazon\elasticsearch\replication\task\index\IndexReplicationTask.kt: (146, 31): Unresolved reference: INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING
e: C:\Codes\ccr-latest\cross-cluster-replication\src\main\kotlin\com\amazon\elasticsearch\replication\task\index\IndexReplicationTask.kt: (802, 36): Unresolved reference: INDEX_PLUGINS_REPLICATION_TRANSLOG_RETENTION_LEASE_PRUNING_ENABLED_SETTING
```

**Comment by ankitkala** [comment]
Hi, 7.10 was based on ES 7.10 and is not supported as an official branch.
