### ISSUE TITLE
[BUG] Builds failing due to compile-time errors introduced in RemoteClusterRepository.kt for Repository class

### ISSUE THREAD

**Issue by aggarwalShivani** [opensearch-project/cross-cluster-replication#1436]
**What is the bug?**
CCR gradle builds are failing with the below mentioned error since yesterday.

```
 ./gradlew assemble
Starting a Gradle Daemon (subsequent builds will be faster)
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 8.4
  OS Info               : Linux 5.15.153.1-microsoft-standard-WSL2 (amd64)
  JDK Version           : 11 (Ubuntu JDK)
  JAVA_HOME             : /usr/lib/jvm/java-11-openjdk-amd64
  Random Testing Seed   : 5C3DD7AD5EFF1789
  In FIPS 140 mode      : false
=======================================

> Task :compileKotlin FAILED
e: file:///path/CCR/opensearch-project-cross-cluster-replication/src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRepository.kt:83:1 Class 'RemoteClusterRepository' is not abstract and does not implement abstract member public abstract fun finalizeSnapshot(p0: ShardGenerations!, p1: Long, p2: Metadata!, p3: SnapshotInfo!, p4: Version!, p5: Function<ClusterState!, ClusterState!>!, p6: Priority!, p7: ActionListener<RepositoryData!>!): Unit defined in org.opensearch.repositories.Repository
e: file:///path/CCR/opensearch-project-cross-cluster-replication/src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRepository.kt:125:5 'finalizeSnapshot' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

```

Details:
Branch: main, Platform: linux

**How can one reproduce the bug?**
1. Clone the latest project git@github.com:opensearch-project/cross-cluster-replication.git 
2. Run gradle assemble
   `./gradlew assemble`

**Do you have any additional context?**
This issue is seen since this PR [#15124](https://github.com/opensearch-project/OpenSearch/pull/15124/files#diff-15dd2c1859d8b3091b1b702af9c5bbdd680224671444870daf9f392d4e838fa1) is merged in Opensearch repo 5d ago. The finalizeSnapshot method of the class Repository.java has an additional new argument Priority which needs to be passed while invoking this function. 
In CCR, the [RemoteClusterRepository.kt](https://github.com/opensearch-project/cross-cluster-replication/blob/2e04b0e4efb4b8e2022464f3cad2f1f28ce71b81/src/main/kotlin/org/opensearch/replication/repository/RemoteClusterRepository.kt) class overrides the finalizeSnapshot method and this now needs to be updated to add Priority field too. 

I locally made this one change and it resolved the gradle build issue.

**Comment by nisgoel-amazon** [comment]
https://github.com/opensearch-project/cross-cluster-replication/pull/1438
This will fix this issue
