### ISSUE TITLE
Onboard to 1.1 Release manifest in opensearch-build.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/cross-cluster-replication#146]
To include CCR inside of the full 1.1 bundle, it will need to be onboarded on to the build system [here](https://github.com/opensearch-project/opensearch-build/tree/main/bundle-workflow).

Requirements:
- [ ] #147 
- Add necessary build.sh script if there is custom build logic for CCR.
- Update the manifest.yml for the 1.1 release inside of opensearch-build repository.

**Comment by saikaranam-amazon** [comment]
Closing this as 1.1 changes are pushed.
