### ISSUE TITLE
Update CI to rely on Snapshots builds of core and common-utils. 

### ISSUE THREAD

**Issue by mch2** [opensearch-project/cross-cluster-replication#147]
Snapshot builds of 1.1 for these repositories are currently being pushed to https://aws.oss.sonatype.org/content/repositories/snapshots/.  We can update gradle scripts to fetch from this repository and remove a checkout & compile step in CI.

**Comment by saikaranam-amazon** [comment]
Closing this as 1.1 changes are pushed
