### ISSUE TITLE
Handle leader cluster disconnection scenarios during bootstrap recovery

### ISSUE THREAD

**Issue by amkhar** [opensearch-project/cross-cluster-replication#16]
**Background**

Cross Cluster Replication uses repository recovery mechanism of OpenSearch to copy the primary shard from leader cluster to follower cluster. It’s like a snapshot restore flow and we can check current status in cat/recovery output. We depend directly on the primary shard node for all file transfers, if that particular node goes down replication fails.

 **Failures :**

* Bootstrap fails if node having primary shard on leader cluster leaves the cluster.
* Bootstrap fails if all nodes of primary cluster are out of service transiently.

**Expected Behaviour**
* Bootstrap should be restarted if primary shard is available on any other node on leader cluster.
* Bootstrap should be failed permanently after all of our retries are exhausted.

**Comment by saikaranam-amazon** [comment]
Pushed as part of 1.1 release.
