### ISSUE TITLE
connect_transport_exception when setup CCR above 2 vps 

### ISSUE THREAD

**Issue by toanpt3** [opensearch-project/cross-cluster-replication#2]
I have successfully installed CCR on same machine, use docker-compose at here: https://opendistro.github.io/for-elasticsearch/blog/releases/2021/02/announcing-ccr/
But not work when setup on two VPS use docker, my setup as  below:
- On VPS1(Leader)
PublicIP: 103.149.180.xxx
DockerIP: 172.18.0.2
CONTAINER ID   IMAGE                                             PORTS 
4215cb76a163     open-distro-for-es-with-replication   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp, 0.0.0.0:9600->9600/tcp, 9650/tcp
- On VPS2(Follower):
PublicIP: 103.149.180.xxx
DockerIP: 172.19.0.2
CONTAINER ID   IMAGE                                             PORTS 
3abdb47cf184     open-distro-for-es-with-replication   0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp, 0.0.0.0:9600->9600/tcp, 9650/tcp   odfe-follower

I run  to step 5 in this guide: https://opendistro.github.io/for-elasticsearch/blog/releases/2021/02/announcing-ccr/  and the error is as below:
curl -k -u testuser:testuser -XPUT \                               
"https://${FOLLOWER}/_opendistro/_replication/follower-01/_start?pretty" \
-H 'Content-type: application/json' \
-d'{"remote_cluster":"leader-cluster", "remote_index": "leader-01"}'
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "connect_transport_exception",
        "reason" : "[odfe-follower1][172.18.0.2:9300] connect_timeout[30s]"
      }
    ],
    "type" : "connect_transport_exception",
    "reason" : "[odfe-follower1][172.18.0.2:9300] connect_timeout[30s]"
  },
  "status" : 500
}
```

**Comment by naviat** [comment]
You need to change the IP addresses for LEADER and FOLLOWER according to your VPSs IP address.

**Comment by ermukesh09** [comment]
I would like to run this on AWS EC2 instance with master and data node on the different instance? Is this achievable in this way?

**Comment by krishna-ggk** [comment]
Sorry, it looks like this got missed and we never took a look. This is actually when CCR was still an experimental ODFE plugin. 

Please try with OpenSearch and if you still face these issues, do reopen this.

> I would like to run this on AWS EC2 instance with master and data node on the different instance? Is this achievable in this way?

Yes, this is supported.
