### ISSUE TITLE
Update integTest gradle scripts to run via remote cluster independently

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/cross-cluster-replication#244]
**Is your feature request related to a problem?**
With the existing implementation of integration tests, opensearch plugins use the same test framework as local integration tests which spin up test clusters by itself. This is a hacky way to override the endpoint from local spun up test clusters (via `opensearch.testclusters` gradle plugin) with the remote cluster endpoint. 

The solution doesn't work when we would like to test the opensearch bundle as part of the release. The test frameworks expect the artifact to be available before we could test them. To clean this up, plugins have to create gradle scripts for remote endpoints to run https://github.com/opensearch-project/opensearch-build#integration-tests for the release cycle. 

**What solution would you like?**
Refer to: https://github.com/opensearch-project/anomaly-detection/pull/298 and make similar changes to the plugin.
Also if you have a custom name to invoke these tests, update the `integtest.sh` script in https://github.com/opensearch-project/opensearch-build/blob/main/scripts/default/integtest.sh

**Comment by ankitkala** [comment]
@saratvemulapalli We'll update the script to run on remote cluster endpoints. But we'd need atleast 2 clusters to test the replication.

**Comment by saratvemulapalli** [comment]
Thats a great point, how does replication plugin test against remote clusters? 
Is it manual today?

For our release automation, I think there are couple of problems to fix:
1. Update the test framework to take in multiple cluster endpoints.
2. Update the test-workflow in opensearch-build to spin up multiple clusters and feed it to replication plugin.
3. Update `integtest.sh` for replication plugin to be custom.

**Comment by saratvemulapalli** [comment]
@ankitkala/ @opensearch-project/replication  this is labeled 2.0. 
What do you guys need to take care of this?

**Comment by ankitkala** [comment]
We've gone ahead with doing sanity on a single cluster for now. Will take this up before next release.
