### ISSUE TITLE
Default CI Java Version to Java 11, run tests on 8, 14 and 17

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#254]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [x] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [ ] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [x] Document Java versions in DEVELOPER_GUIDE.md.

**Comment by dblock** [comment]
@naveenpajjuri what else is left to do to close this for 1.3.0?

**Comment by naveenpajjuri** [comment]
Currently we have CI support for 8,11 and 14. with default version as 11.
We need to support JDK 17 as well, for which we need to upgrade gradle version to 7, which currently needs work (https://github.com/opensearch-project/cross-cluster-replication/issues/330).

@dblock : Should we close this as i see you have already opened an issue for JDK 17 support (https://github.com/opensearch-project/cross-cluster-replication/issues/331)
