### ISSUE TITLE
New issues in this repo should get an untriaged label

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#255]
**Is your feature request related to a problem? Please describe.**
New issues that haven't been looked at cannot be distinguished. I manually added an untriaged label for this one, but this should be automatic.

**Describe the solution you'd like**
Similar to other plugins, change templates to create issues with "untriaged" label to sort through what's new.

**Comment by saikaranam-amazon** [comment]
@dblock - Added missing label as part of this PR: https://github.com/opensearch-project/cross-cluster-replication/pull/260
Closing this issue.
