### ISSUE TITLE
[QUESTION] Repository with plugin ZIP

### ISSUE THREAD

**Issue by mrMigles** [opensearch-project/cross-cluster-replication#258]
Hello,

First of all, thank you for this awesome plugin! 

I have a question about plugin's repository. In my company we install plugin from our own internal repository (we haven't access to public), se we have to mirror plugin's ZIPs to our own. 
Previously we did the same for OpenDistro cross-cluster-replication plugin "https://github.com/opendistro-for-elasticsearch/cross-cluster-replication/releases/download/v1.13.0.0-experimental/opendistro-cross-cluster-replication-1.13.0.0.zip" or Elasticsearch plugin for S3 from here "https://artifacts.elastic.co/downloads/elasticsearch-plugins/repository-s3/repository-s3-6.8.15.zip".

Do you have public repository for your builds of plugins? 

Because in your docs we found [corrupted link](https://github.com/opensearch-project/cross-cluster-replication/blob/main/HANDBOOK.md#install-cross-cluster-replication-plugin):

```
#TODO: Update repo
sudo bin/opensearch-plugin install \
https://github.com/opensearch-project/cross-cluster-replication/releases/download/v1.1.0.0/opensearch-cross-cluster-replication-1.1.0.0.zip
```

**Comment by krishna-ggk** [comment]
Thanks for bringing this to our notice. The appropriate link is https://github.com/opensearch-project/cross-cluster-replication/archive/refs/tags/1.1.0.0.zip for 1.1.

We will update the handbook with appropriate verbiage so that the instructions apply for all versions.

**Comment by mrMigles** [comment]
@krishna-ggk, thank you!

**Comment by dblock** [comment]
Note that this .zip is not signed. Please add a +1 to https://github.com/opensearch-project/opensearch-build/issues/517 and https://github.com/opensearch-project/opensearch-build/issues/716.
