### ISSUE TITLE
[BUG] Avoid excessive logging during certain exception types

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#267]
**Describe the bug**
Relevant exceptions(5xx) are retried under the common module and during this time whole stack trace is logged under "WARN". 
For certain operations, this can create excessive logging and creates noise. 

**To Reproduce**
1. Start the replication
2. Once the follower catches-up, Don't index any data at the leader
3. See that the TimeoutExceptions are logged at the follower. These are logged after every timeout for the idle indices.  

**Expected behavior**
Filter out the exceptions types and log minimally to avoid the noise

**Comment by mohitamg** [comment]
will take this up
