### ISSUE TITLE
[BUG] CI is failing

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#279]
**Describe the bug**
PRs are being merged with failing CI, e.g. https://github.com/opensearch-project/cross-cluster-replication/runs/4688022016?check_suite_focus=true

**Expected behavior**
Passing CI before any more changes are made.

**Comment by saikaranam-amazon** [comment]
Tracking test failure issue in https://github.com/opensearch-project/cross-cluster-replication/issues/280

**Comment by saikaranam-amazon** [comment]
Resolving this issue as the changes are pushed to both main and 1.2 branches
