### ISSUE TITLE
OpenSearch changes for replication

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#30]
### Description
If local build fails, 

1. Please download and copy the following artifacts under maven local cache.
  - `For integ tests: ~/.gradle/caches/modules-2/files-2.1/org.elasticsearch.distribution.integ-test-zip/7.10.2/<hash>/*.zip`
  -  `For local build: ~/.gradle/caches/modules-2/files-2.1/org.elasticsearch/elasticsearch/7.10.2/<hash>/*.jar`

**Comment by ankitkala** [comment]
Use JDK 14 to build the 7.10 branch.
