### ISSUE TITLE
Change the "Master" nomenclature 

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/cross-cluster-replication#319]
**Is your feature request related to a problem? Please describe.**
[OpenSearch](https://github.com/opensearch-project/OpenSearch) repository is going to replace the terminology "master"with "cluster manager".
issue: https://github.com/opensearch-project/OpenSearch/issues/472, with the plan for its terminology replacement.

Although the existing usages with "master" will be supported in OpenSearch version 2.x until further notice to keep the backwards compatibility, it's suggested to prepare for the nomenclature change in advance, and replace all the usages with "master" terminology in the code base.

**Describe the solution you'd like**

The replacement plan for OpenSearch repository can be taken as a reference: https://github.com/opensearch-project/OpenSearch/issues/472#issuecomment-960298995

Replace the  terminology "master" with "cluster manager" in
1. Code comment and internal variable/method/class/package name
2. Reference to OpenSearh Java API, when OpenSearch make the changes in at least version 3.0.0

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by naveenpajjuri** [comment]
Renamed master to Cluster Manager where ever possible in variable, class names and updated the documentation accordingly.

**Comment by tlfeng** [comment]
After searching the keyword in the repository through GitHub, I found there are several Java APIs still need to be replaced before version 3.0, and I updated in the issue description, please take a look at. Thank you 👍
