### ISSUE TITLE
[BUG] Confusing error message when starting replication without specifying leader index

### ISSUE THREAD

**Issue by rushiagr** [opensearch-project/cross-cluster-replication#320]
**Describe the bug**
When one tries to replicate an index but doesn't specify index name, it throws `uninitialized_property_access_exception` with message `lateinit property leaderIndex has not been initialized`. The message could have been clearer. 

**To Reproduce**
1. Run `curl -sku $creds "$follower/_plugins/_replication/index1/_start?pretty" -XPUT -H "content-type: application/json" --data '{"leader_alias" : "remote-cluster", "use_roles": {"leader_cluster_role": "all_access", "follower_cluster_role": "all_access"}}'`

**Expected behavior**
Error message which says something on the lines of `please specify "leader_index"`

**Plugins**
Standard ElasticSearch 7.10, AWS-hosted domain.

**Screenshots**
Output:

```
% curl -sku $creds "$follower/_plugins/_replication/index1/_start?pretty" -XPUT -H "content-type: application/json" --data '{"leader_alias" : "remote-cluster", "use_roles": {"leader_cluster_role": "all_access", "follower_cluster_role": "all_access"}}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "uninitialized_property_access_exception",
        "reason" : "lateinit property leaderIndex has not been initialized"
      }
    ],
    "type" : "uninitialized_property_access_exception",
    "reason" : "lateinit property leaderIndex has not been initialized"
  },
  "status" : 500
}
```

**Host/Environment (please complete the following information):**
MacOS Big Sur

**Additional context**
None

**Comment by monusingh-1** [comment]
Resolved
