### ISSUE TITLE
Replace checked-in ZIPs with dynamic dependencies

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#335]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1750, replace checked in zip with a dynamic dependency.

```
./cross-cluster-replication/src/test/resources/replication/opensearch-cross-cluster-replication-1.1.0.0.zip
```

**Comment by naveenpajjuri** [comment]
@dblock We are dependent on CCR Artefacts to be published to maven for us to use it as a dynamic dependency.
Unlike other plugins we don't have artefacts published to cloudfront (in Odfe).
So we can only pick this issue after our artefacts are there on Mvn, so deferring this from 2.0

**Comment by naveenpajjuri** [comment]
removing 2.0 tag from this issue, as there is a dependency (as per my previous comment).

**Comment by dblock** [comment]
Thanks for removing the ZIP in https://github.com/opensearch-project/cross-cluster-replication/pull/366, @naveenpajjuri. That was the right thing to do (comments above say otherwise).
