### ISSUE TITLE
Add error logs for when the index replication task moves to paused or failed

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#345]
Add error logs for when the index replication task moves to pausd or failed. 

This would be useful for customers monitoring the error logs to identify any issue with replication.

**Comment by elfisher** [comment]
Is this related to https://github.com/opensearch-project/cross-cluster-replication/issues/350?

**Comment by ankitkala** [comment]
Yes. Closing this as duplicate.
