### ISSUE TITLE
[BUG] OpenSearchTimeoutException after initial good replication

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/cross-cluster-replication#362]
**Describe the bug**
I have two clusters within k8s, different namespaces. Creating the initial replication goes well: indices are replicated instantly. Within a few minutes the logs are flooded with OpenSearchTimeoutException for every index I try to replicate. Connection should be fine, if I stop replication for one index, delete it and reinitialize; it's fine.
```

PUT _cluster/settings
{
  "persistent": {
    "cluster": {
      "remote": {
        "alias": {
          "seeds": ["opensearch-master-nodes.mdtis-servicelayer-prd:9300"]
        }
      }
    }
  }
}

PUT _plugins/_replication/index/_start?pretty
{
   "leader_alias": "alias",
   "leader_index": "index",
   "use_roles":{
      "leader_cluster_role": "all_access",
      "follower_cluster_role": "all_access"
   }
}

```

Error:
![image](https://user-images.githubusercontent.com/2643715/162638851-2d1a7511-449a-455b-85e3-d330d54b3be3.png)

**Expected behavior**
Replication remains working

**Plugins**
Default docker image plus S3 and Azure plugins

**Screenshots**

**Host/Environment (please complete the following information):**
Opensearch 1.3.1 docker image everywhere
Kubernetes
Two namepaces, 1 for prod, 1 for replication
Replication cluster points to k8s service in front of the master nodes of the production cluster

**Additional context**

**Comment by saikaranam-amazon** [comment]
Thanks @ict-one-nl for surfacing the issue.
we are tracking the issue here: https://github.com/opensearch-project/cross-cluster-replication/issues/267

During the polling from leader, this exception is logged and we are working to remove this excessive logging.
Replication is working fine during this case as well.

**Comment by saikaranam-amazon** [comment]
Closing this as the fix is being worked upon in the related issue.
