### ISSUE TITLE
[FEATURE] Run integration tests as part of the OpenSearch distribution

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#383]
**Is your feature request related to a problem?**
Following a problem in another plugin (https://github.com/opensearch-project/opensearch-build/issues/2043), and coming from https://github.com/opensearch-project/opensearch-build/issues/58, there's no automated testing that this plugin runs as part of the OpenSearch distribution.

**What solution would you like?**
Run integration tests as part of the distribution.

**Comment by ankitkala** [comment]
Just to confirm, do we want to add the jenkins workflow per plugin to run the integration tests? Or is the ask to implement a generic script (like `test.sh`) as an entrypoint to run different tests based on the arguments .

**Comment by manishdev-amzn** [comment]
This requires brining up 2 clusters and cross cluster integration script will use these enndpoints for testing. To address this, build system team will require to make changes in bringing up the clusters and cross cluster team will makes changes to integration tests. We are targeting CCR repo level changes provided the build level changes are in place . Can build system team provide the build infra level changes?   CC: @dblock @CEHENKLE

**Comment by manishdev-amzn** [comment]
Related issue: https://github.com/opensearch-project/cross-cluster-replication/issues/244#issuecomment-970644251

**Comment by Pallavi-AWS** [comment]
@dblock  we will add basic testcase to check sanity of distribution build by checking plugin installation. This can be done by invoking a plugin API (_start, follower_stats) and validate failure. Any functionality around replication still needs more than one cluster in the framework, which we will manually verify when docker artifacts are ready (@ankitkala, @saikaranam-amazon)

**Comment by dblock** [comment]
@Pallavi-AWS I assigned this to you so we don't drop it, please reassign this issue and #244 as you see fit.

**Comment by dblock** [comment]
@Pallavi-AWS The multiple cluster work is https://github.com/opensearch-project/opensearch-build/issues/1428

**Comment by ankitkala** [comment]
@dblock The multi cluster support mentioned above is for performance tests where we're spinning up the clusters on dedicated ec2 nodes using CDK. 
I think for integ tests, we rely on `LocalTestCluster`: https://github.com/opensearch-project/opensearch-build/blob/main/src/test_workflow/integ_test/integ_test_suite_opensearch.py#L67
