### ISSUE TITLE
[cross-cluster-replication] OpenSearch 2.0 Changes

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#397]
Targeted fixes for OS 2.0 release
- https://github.com/opensearch-project/cross-cluster-replication/issues/346
- https://github.com/opensearch-project/cross-cluster-replication/issues/331
- https://github.com/opensearch-project/cross-cluster-replication/issues/319
- https://github.com/opensearch-project/cross-cluster-replication/pull/358
- https://github.com/opensearch-project/cross-cluster-replication/pull/365
- https://github.com/opensearch-project/cross-cluster-replication/pull/366
- https://github.com/opensearch-project/cross-cluster-replication/pull/370

**Comment by saikaranam-amazon** [comment]
Closing this issue as changes are merged.
