### ISSUE TITLE
[BUG] Mapping updates on leader with strict dynamic setting results in auto pause of replication

### ISSUE THREAD

**Issue by krishna-ggk** [opensearch-project/cross-cluster-replication#409]
### What is the bug?

For an actively replicating index, if the mapping is updated on the leader with dynamic set to `strict`, replication auto-pauses with following exception

```bash
curl -k -XGET -u $CREDS -s "$FOLLOWER/_plugins/_replication/follower-02-strict/_status?pretty"
{
  "status" : "PAUSED",
  "reason" : "AutoPaused: [[follower-02-strict][0] - org.opensearch.index.mapper.StrictDynamicMappingException - \"mapping set to strict, dynamic introduction of [place] within [_doc] is not allowed\"], ",
  "leader_alias" : "my-leader-1",
  "leader_index" : "leader-02-strict",
  "follower_index" : "follower-02-strict"
}
```

#### 1. Create test leader index with dynamic set to strict

```bash
curl -k -XPUT -u $CREDS -s "$LEADER/leader-02-strict?pretty" -H \
'Content-Type: application/json' \
-d'{"mappings":{"dynamic":"strict","properties":{"name":{"type":"text"}}}}'
```

#### 2. Start replication

```bash
curl -sku "${CREDS}" -XPUT "${FOLLOWER}/_plugins/_replication/follower-02-strict/_start?pretty" \
-H 'Content-Type: application/json' \
-d '{"leader_alias":"my-leader-1", "leader_index": "leader-02-strict", "use_roles": { "leader_cluster_role": "all_access", "follower_cluster_role": "all_access" } }'
```

#### 3. Update mapping on leader and ingest new doc using the updated mapping

```bash
curl -k -XPOST -u $CREDS -s "$LEADER/leader-02-strict/_mapping?pretty" \
-H 'Content-Type: application/json' \
-d'{"dynamic":"strict","properties":{"name":{"type":"text"},"place":{"type":"text"}}}' &&
curl -k -XPOST -u $CREDS -s "$LEADER/leader-02-strict/_doc/3" \
-H 'Content-Type: application/json' \
-d '{"name" : "dummy data1","place":"home"}'
```

#### 4. Replication Status

```bash
curl -k -XGET -u $CREDS -s "$FOLLOWER/_plugins/_replication/follower-02-strict/_status?pretty"
{
  "status" : "PAUSED",
  "reason" : "AutoPaused: [[follower-02-strict][0] - org.opensearch.index.mapper.StrictDynamicMappingException - \"mapping set to strict, dynamic introduction of [place] within [_doc] is not allowed\"], ",
  "leader_alias" : "my-leader-1",
  "leader_index" : "leader-02-strict",
  "follower_index" : "follower-02-strict"
}
```

### What is the expected behavior?

It looks like the mapping updates aren't propagated immediately and any data with additional field results in exception that halts replication.

Ideally the replication engine should handle mapping updates seamlessly even with dynamic set to `strict`.

**Comment by ankitkala** [comment]
We sync the mapping from leader shard if the `applyTranslogOperation` returns result type as `MAPPING_UPDATE_REQUIRED`: https://github.com/opensearch-project/cross-cluster-replication/blob/4f790d20eeefe78f00c0810501e73bc2b5dfc1ef/src/main/kotlin/org/opensearch/replication/action/replay/TransportReplayChangesAction.kt#L123

In this particular case, `IndexShard` simply rejects the request as dynamic mapping is set to strict. We need additional handling for `StrictDynamicMappingException`(or even the parent exception `MapperParsingException`). Incase we encounter this exception, we should sync the mapping again from leader and retry.
