### ISSUE TITLE
[ENHANCEMENT] Support for indices clean-up after the test runs

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#412]
**Is your feature request related to a problem?**
Yes, Currently, It is the test runners responsibility to clean-up the indices and stop the replication before proceeding with the next runs. This introduces lot of redundant code for every tests.

**What solution would you like?**
Integ test framework should handle the issue and completely wipe-out the cluster before every test run and any failures from the previous runs should be flagged appropriately.

**Comment by saikaranam-amazon** [comment]
These changes are already part of the v2.5.0.
Removing the v2.5.0 label

**Comment by sricharanvuppu** [comment]
Backported to all major versions.
