### ISSUE TITLE
[cross-cluster-replication] OpenSearch 2.1 Changes

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#433]
Targeted fixes for OS 2.0 release
- https://github.com/opensearch-project/cross-cluster-replication/pull/419
- https://github.com/opensearch-project/cross-cluster-replication/pull/341
- https://github.com/opensearch-project/cross-cluster-replication/pull/411
- https://github.com/opensearch-project/cross-cluster-replication/pull/408

**Comment by saikaranam-amazon** [comment]
As the changes are merged, Closing this issue
