### ISSUE TITLE
Make this repo public

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#47]
This repo is mentioned in https://github.com/opensearch-project/project-website/pull/184/files#diff-c01a7cdc2142d66cae9e5cac47ddf1e2fda2477465dbf1943ca17b4c9897beadR52 but is private. Any reason why we are developing it in closed source? Let's make this repository public after all the usual IP review and that kind of stuff.

**Comment by varunsrivathsav** [comment]
The repo is now public.
