### ISSUE TITLE
[BUG] Shard replication tasks do not start on new nodes intermittently

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/cross-cluster-replication#482]
**What is the bug?**
When a node is replace with another node and the shard migrates to the new node, the shard replication task does not start sometimes which results in replication not working.

The bug is in this [code](https://github.com/opensearch-project/cross-cluster-replication/blob/main/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L346-L348) where the index task checks for shard tasks for all indices. Even if one shard task is present for any other index it bails out. This code should be modified to check the shard tasks for the particular index only.

**How can one reproduce the bug?**
1. Start replication for atleast 2 indices
2. Add a new node to the cluster
3. Shutdown ES on the node where the index replication task is running
4. Index replication task should start on any of the new nodes
5. Shard replication task may not start on the new node(May have to repeat to this simulate the issue as it is intermittent)

**What is the expected behavior?**
Index and Shard replication task should start after they are stopped due to node replacement

**Comment by krishna-ggk** [comment]
Thanks for finding the bug and root-causing it.

One thing to re-evaluate is whether we can unify code-path to start missing shard tasks.
1. When shard tasks are missing for all shards. ([link](https://github.com/opensearch-project/cross-cluster-replication/blame/main/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L350))
2. When shard tasks are missing for few shards. ([link](https://github.com/opensearch-project/cross-cluster-replication/blame/main/src/main/kotlin/org/opensearch/replication/task/index/IndexReplicationTask.kt#L210))

**Comment by ankitkala** [comment]
I've raised the PR for fixing the bug where we weren't filtering the ShardReplicationTasks for current index: https://github.com/opensearch-project/cross-cluster-replication/pull/497

We should still keep this issue open to refactor and unify the logic to spawn the missing/all shard tasks

**Comment by ankitkala** [comment]
Closing the issue as we've also addressed the refactoring as part of same PR.
