### ISSUE TITLE
[ENHANCEMENT] Move replication metadata from hidden index to system index

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#487]
CCR metadata should be moved to system index instead of hidden index which is a legacy way of maintaining system indices. 
Some of the benefits are called out [here](https://github.com/opensearch-project/OpenSearch/issues/3942). 

Keeping this issue to track the changes and discuss the migration path

**Comment by monusingh-1** [comment]
Closing as resolved
