### ISSUE TITLE
Supports bidirectional replication.

### ISSUE THREAD

**Issue by Shams-yang** [opensearch-project/cross-cluster-replication#5]
In some cases, if the active cluster is faulty, the standby cluster needs to take over services temporarily. After the primary cluster recovers, data generated during this period needs to be synchronized from the standby cluster to the primary cluster. Therefore, bidirectional replication needs to be supported. Here's what we need to do：

1. No longer checks whether the same index is being used in IndexReplicationExecutor .

2. Remove INDEX_REPLICATION_BLOCK when removeing AutoFollow.

**Comment by krishna-ggk** [comment]
Currently we don't plan to support bidirectional connection directly, but instead support failover with full-cluster replication - https://github.com/opensearch-project/cross-cluster-replication/issues/549

Please leave us feedback over there.
