### ISSUE TITLE
Move the CCR performance tests to the new ci.amazon.com

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#509]
We have a periodic performance run for CCR to benchmark the replication performance. We need to move the workflow to the new setup i.e. buld.ci.amazon.com

**Comment by ankitkala** [comment]
Mohit is working on it.

**Comment by mohitamg** [comment]
Have started working on it, performance testing on single node cluster and multi node cluster is completed.
