### ISSUE TITLE
[RFC] Full Cluster Replication with Failover &  Failback support

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#549]
**What problems are you trying to solve?**
Cross cluster replication, as it stands today, allows user to setup continuous replication on a set of indices from one cluster(leader) to another(follower). This happens right now at index level where customer can choose to enable replication on a particular index/pattern. 
We rely on a logical replication model where each shard on follower index polls the leader shard for new changes(i.e. translog) which it then replays locally. 

**Problem statement:** While the current implementation works fine, it is not feature complete. From a users point of view, we need cluster level replication with support for Failover/Failback. This proposal lists down the high level approach and the plan for achieving Full Cluster Replication with Failover and Failback support.

---
**Why should it be built? Any reason not to?**
These are the major use cases for Full Cluster Replication:
1. **Disaster Recovery**: Full Cluster Replication can be very useful for building tolerance against outages or complete failure of OpenSearch clusters. With Full cluster replication, user can setup backup clusters that continuously replicate data from the primary cluster and are ready to serve the production workload in case of Primary cluster outage.
2. **Data Proximity**: For search use cases, a single centralised cluster serving requests for end users across multiple regions increases the end to end latency . With Full Cluster Replication, cluster owners can configure multiple read-only clusters in closer proximity to the end users thus enhancing the overall customer experience. 

---
**What are you proposing?**
We propose building support for Full Cluster Replication on OpenSearch. During Replication, Secondary clusters would periodically poll the primary for data (indices, index settings, index mapping, cluster settings, cluster state, etc). Duration for poll should be small enough to ensure the minimal lag(e.g. 1 min) in propagating these changes to the Secondaries. Incase of remote store, this flow can be further optimised such that all secondary clusters can fetch the data directly from remote store thus reducing the overhead of replication on leader.

![Data proximity](https://user-images.githubusercontent.com/1824124/190313795-88f51a77-b0e5-45fc-8f2e-4f6850fe6e44.png)
![DR](https://user-images.githubusercontent.com/1824124/190313790-77d0e141-24da-4075-b36f-2a511e72a05c.png)
![DR Failover](https://user-images.githubusercontent.com/1824124/190313784-659e0b13-b7f0-4368-a7ee-9c897e94cffe.png)

Apart from customer data, we'd be replicating system indices as well. We'll work with other plugins(Dashboards, Security, ISM, etc) to ensure integration with Full Cluster Replication. For example, security plugin on secondary clusters should be able to work as expected with the replicated security plugin metadata from Primary. 

**Handling Failover/Failback:** 
Failover and Failback will be a manual customer invoked action. We can be further explore automating it via an external process but it's not planned as of now. 
Individual clusters would have the capability to switch its role between Primary/Secondary but won’t be smart enough to do this switch automatically.

*Why not automatic failover?* To achieve auto-failover internally we'll need to establish a quorum between the Primary and Secondary clusters which will significantly increase the complexity of the replication process. On top of that, Replication will be more prone to failure in outages like network partition, as clusters might not be able to establish the quorum and thus fail to do the failover(similar to split-brain).

---
**What is the user experience going to be?**
User stories:
- As a cluster admin, I want to continuously replicate all the data from my Primary cluster to multiple Secondary clusters so that my end users experience low search latency by requesting data from the nearest cluster.
- As a cluster admin, I want to continuously replicate all the data from my Primary cluster to multiple Secondary clusters so that I  have backup cluster ready to serve traffic in case of any outage on Primary.
- As a cluster admin, I want to switch the Replication Configuration so that I can promote one of the Secondary cluster as the new Primary incase of Failover/Failback. 

*Note*: While we'll support multiple secondary clusters replicating from a primary, we won't support chained replication(secondary cluster replicating to another cluster)

---

**Other dependencies:** 
*Choice of Replication model*: Although the choice of replication model shouldn't affect Full Cluster Replication design drastically, it'll still require us to build support for multiple scenarios and we might want to restrict the choice of replication model for Full Cluster Replication. The preference for replication model is mentioned below(highest on top). 
1. Segment replication with remote store
2. Segment replication without remote store
3. Logical replication

Note: The preference above is not backed by any benchmark but rather based on our performance expectations from prior experiences. We'll cover this in more detail during design.

**Comment by krishna-ggk** [comment]
Thanks for the great writeup @ankitkala 

Few open questions
1. Does the follower cluster need to have exact same topology configuration as leader cluster?
2. Similar to 1, what about version constraints and other configs? Are they expected to match? (I understand this will open up problem up version upgrades coordination)
3. Are there sample APIs if already thought about to demonstrate the user workflows?
4. Can the replication direction switch back and forth when the failover happens?

**Comment by ankitkala** [comment]
> Does the follower cluster need to have exact same topology configuration as leader cluster?

It is recommended (at least for DR cases) but we might not be able to enforce it. At the least, secondary should have enough space to accommodate the Primary's data.

> Similar to 1, what about version constraints and other configs? Are they expected to match? (I understand this will open up problem up version upgrades coordination)

Depends on choice of replication, For SegRep based approaches, we'll need to enforce that the version matches across Primary and secondary. 

> Are there sample APIs if already thought about to demonstrate the user workflows?

We need to discuss those as part of design and probably can then come up with sample APIs.

> Can the replication direction switch back and forth when the failover happens?

Yes. Replication direction has to switch back and forth during failover and failback.

**Comment by saikaranam-amazon** [comment]
Lets add further details on - 
 - For Data proximity case, 
     - Additional details on support of secondary clusters replicating from multiple primary clusters. 
       - How will the support of failover looks in this case?
 - Can we add expectation on achievable(/target) RPO and RTO at cluster-level with this feature?

**Comment by kgcreative** [comment]
> **What is the user experience going to be?**
> User stories:

This should be "As a cluster admin, I want to continuously replicate all the data from my Primary cluster to multiple Secondary clusters so that my end users experience low search latency by requesting data from the nearest cluster."

**Comment by elfisher** [comment]
This is a very detailed proposal. Thanks @ankitkala! I have a few comments/quesitons:
1. Will this be enabled on the replica cluster? When a replica cluster is setup, is there a cluster wide setting we can use as an indicator in the UX that it is acting as a follower cluster?
2. With remote store enabled on the primary, will the recovery point objective (RPO) be 0?
3. From a UX perspective, we should plan a UI in the management tools section of Dashboards to manage CCR.
4. If a cluster is set to primary and the previous cluster that was a primary comes back online, will the new primary ignore it? 
5. How do we reconcile multiple followers when the primary changes?
6. In the automatic failover, I think it is worth calling out one other aspect that makes this challenging is that traffic, load balances, and other systems will need to be rerouted which isn't managed by the OpenSearch process.

**Comment by ankitkala** [comment]
> Can we add expectation on achievable(/target) RPO and RTO at cluster-level with this feature?

Yep. I deliberately not mentioned it here as RPO will heavily depend on how we want to design the complete solution. I'll update those here after we have more clarity on what we want to support.
RTO might be even more tricky given that we want to start with manual Failover/Failback

**Comment by elfisher** [comment]
One other question is that there seems to be two features 1/ enabling full cluster replication and 2/ failover/failback. Do we want to split these into two releases since they are two features? Would that help accelerate releasing the full cluster replication capability?

**Comment by dblock** [comment]
This is very thorough. Looking forward to a proposal for APIs. 

- Need a section on conflict resolution, especially in failover scenarios. If the leader cluster is failing, you may fail over, then fail back, and end up with different data on the two clusters.
- Consider whether replication may want to expose replication write concerns to the write APIs (e.g. return when "majority" or "at least 1" of the replicas has received/written/committed data).

**Comment by ankitkala** [comment]
> Will this be enabled on the replica cluster? When a replica cluster is setup, is there a cluster wide setting we can use as an indicator in the UX that it is acting as a follower cluster?

It'll have to be introduced. How we're thinking of this is that cluster can behave in 2 mode(Primary and Secondary). We'll definitely need to provide that visibility to the customers.


> With remote store enabled on the primary, will the recovery point objective (RPO) be 0?

We'd want to be as close to 0 as possible. We can revisit this we have basic high level design ready.

> From a UX perspective, we should plan a UI in the management tools section of Dashboards to manage CCR.

Agreed. 

> If a cluster is set to primary and the previous cluster that was a primary comes back online, will the new primary ignore it?
How do we reconcile multiple followers when the primary changes?

We'll need to have a simplistic version of primary term to deterministically identify who is the new Primary. 

> In the automatic failover, I think it is worth calling out one other aspect that makes this challenging is that traffic, load balances, and other systems will need to be rerouted which isn't managed by the OpenSearch process.

Incase of DR, we're not thinking about distributing the load in any way. Instead, Secondary would be on complete standby .

**Comment by anasalkouz** [comment]
Thanks for the thorough proposal.
> Individual clusters would have the capability to switch its role between Primary/Secondary but won’t be smart enough to do this switch automatically.
 Does the customer need to switch their indexer (indexing operations) to the secondary cluster manually? How to handle failed indexing operations during the primary's cluster outage.

**Comment by ankitkala** [comment]
> Does the customer need to switch their indexer (indexing operations) to the secondary cluster manually? How to handle failed indexing operations during the primary's cluster outage.

Yes, Customer has to manually failover to one of the secondary cluster. There is expected to be some data loss in case of failover due to an outage(based on our RPO guarantees). Post failover, customer can continue indexing the data to the follower cluster.

**Comment by zalseryani** [comment]
Greetings, 

Any update on this ? 

Is there any progress related to RPO and RTO ? 


Thank you.
