### ISSUE TITLE
[BUG] Two followers using same remote alias can result in replication being auto-paused

### ISSUE THREAD

**Issue by krishna-ggk** [opensearch-project/cross-cluster-replication#554]
**What is the bug?**

Currently, "{remote-alias}:{followerShardId}" is used as retention lease identifier which results in overlapping usage when two followers are configured for same leader domain with same remote-alias.

The retention lease identifier should include a follower cluster specific identifier (a UUID) to further disambiguate this.

**Comment by soosinha** [comment]
The retention lease ID is of the form `replication:<followerClusterName>:<indexName[shard number]>`([code reference](https://github.com/opensearch-project/cross-cluster-replication/blob/cafc069dd6b83182cf306cfea19f72ea1966ccb5/src/main/kotlin/org/opensearch/replication/seqno/RemoteClusterRetentionLeaseHelper.kt#L39))
So if the follower cluster names are same and even though remote cluster aliases are different, the retention lease ID will be same and will cause conflict.

**Comment by soosinha** [comment]
One more way to repro is to stop replication on one follower. Then the replication on 2nd follower should get auto-paused with retention lease not found exception.

**Comment by monu-aws** [comment]
Merged changes.
