### ISSUE TITLE
[FEATURE] Residual replication tasks should be cancelled on replication start/resume

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/cross-cluster-replication#571]
**Is your feature request related to a problem?**
When replication is paused, sometimes the replication tasks do not clear up.

**What solution would you like?**
When resuming or starting replication, any residual tasks from previous replication should be cancelled.

**Comment by saikaranam-amazon** [comment]
Let's address this as part of `_stop` API to clean any dangling resources.

**Comment by monusingh-1** [comment]
This is resolved https://github.com/opensearch-project/cross-cluster-replication/pull/905
