### ISSUE TITLE
RPO & RTO requirements for Full Cluster Replication

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#590]
- **Recovery Point Objective(RPO)**: Maximum targeted period for which data might be lost during Disaster Recovery(i.e. Failover).
- **Recovery Time Objective(RTO)**: Maximum time duration it takes for clusters to achieve Failover. During this period, clusters will not accept writes. 

Open Questions:
- [ ] What are the minimum RPO & RTO guarantees we want to support?
- [ ] For cross-region use cases, how do we handle network partitioning during failover?

**Comment by ankitkala** [comment]
Ideally we'd want to have minimal RPO & RTO. 

To achieve zero RPO(i.e. no data loss) & near-zero RTO, we'd need to move towards a synchronous replication model where writes on primary are not acknowledged unless one of the secondary has also accepted the write operation. This ensures that one of the secondary is always consistent with Primary and can be used for failover ensuring no data loss.
However this approach would affect the availability of the Primary(consistency vs availability in CAP theorem).

We propose relying on an asynchronous replication model where user can define its RPO & RTO requirements. 
Let's assume we're using Segment Replication with Remote Store. We can piggyback on local cluster level durability guarantees to ensure minimal RPO. 
For example, as soon as segments are written to Primary's remote store(with refresh or commit), these changes are always available to the secondary clusters. Incase of Primary outage, secondary can ensure that all the latest segments have been downloaded. As an additional step during failover, we can even explore fetching primary's translog to ensure no data loss. This would ensure we have near-zero RPO & RTO in happy cases.

In the worst case scenario, let's assume that there is is network partitioning and Secondary can't read the remote store data. 
- **Case 1:** Customers okay with acceptable data loss can achieve failover immediately(near-zero RTO).  RPO in this case would directly related to replication lag between Primary & Secondary.
- **Case 2:** Customers not okay with data loss will require higher RTO as they have to wait till the network partitioning s resolved. Just to remind, the primary cluster might still be unavailable here. So technically you can achieve your zero RPOs but  you'll take a hit on your RTO..
  - One optimisation over this could be to rely on the remote store's capability for cross region replication. With this approach, data from Primary's remote store is replicated directly to the Secondary's remote store and secondary cluster can fetch data directly from its remote store. In this case, if a network partition happens, we can rely on underlying remote store's guarantees(e.g. S3 guarantees 15 mins for 99.99) for ensuring that the data is available to the Secondary clusters.

**Comment by ankitkala** [comment]
For other approaches, we can only ensure RPO equals to our SLA for Replication lag. 
To ensure that failover can be achieved with our RPO & RTO guarantees, we'd need 2 things: 
- Have metrics and APIs to ensure that Replication setup is in healthy state(i.e. Replication active and lag within the SLA)
- Incase the replication lag is high, we'd also need the necessary tuning parameters which can be leveraged to ensure we meet the Replication lag SLA.

**Comment by rohin** [comment]
Zero **RPO** is a must have for any business critical application. It is possible to achieve Zero RPO for OpenSearch but there can be trade-offs, you can use synchronous writes with enough redundancy to ensure you have zero RPO within a domain.  For cross-domains we can use one of the following option
1. Provide synchronous replication across clusters with consensus replication. i.e. Primary will not acknowledge a write request till all the secondary cluster acknowledge the write request. It could also mean that the common remote data store has acknowledged the write request.
2. Provide synchronous replication across domains with Quorum based replication i.e. Primary will acknowledge a write request if a majority of the secondary cluster acknowledges the write request.

For users who are okay with some data loss, the in-cluster replication and cross-cluster replication can be treated independently. The lag between domains would be equivalent to the RPO. This also provides the opportunity to use different strategy to determine how you want to achieve replication. Do you do it event based, frequency based, size based etc. The design should provide some level of control for the same.

RTO can be tricky. What would we consider as RTO? At a basic RTO is the time it takes a system to recover from a failure event. A system should try and minimize the RTO. In which case it is important that 
1. the mean time to detect failure is low, 
2. time it takes to start recovery is low, 
3. the time it takes to reconcile the data is low or data reconciliation should be fast.

In each of the above case we need to ensure we have the appropriate events, metrics and process. 

Failure Detection - Full cluster failure, node failure, network failure, can all impact the ability to replicate and hence need to be detected fast. It could be a combination of health pings between clusters, latency, replication lag and timeouts.

Recovery - If we look at a fully managed experience, it should include ability to do a failover in case a primary cluster is impacted. While the failover happens, primary cluster may need to recover. This recovery will require that first it is established that the cluster up and running and it catches back to the current state of data in the group of clusters.

**Comment by krishna-ggk** [comment]
Thanks for the great discussion!

I'd like to dig-in a bit on Zero RPO. Totally understand why critical business would require 0 RPO.


> * Provide synchronous replication across clusters with consensus replication. i.e. Primary will not acknowledge a write request till all the secondary cluster acknowledge the write request. It could also mean that the common remote data store has acknowledged the write request.
> 
> * Provide synchronous replication across domains with Quorum based replication i.e. Primary will acknowledge a write request if a majority of the secondary cluster acknowledges the write request.

Like pointed, synchronous replication is the **only way** to implement 0 RPO as one needs to ensure the copies are replicated to other cluster which could be in other region.

Is it fair to assume typical cross-cluster replication deployments for DR usecases are across regions? Picking AWS regions as an [example](https://www.cloudping.co) (unofficial), latency between us-east-1 & us-west-2 is about 60 ms while between same regions is about 4 ms. Similarly picking [Azure](https://learn.microsoft.com/en-us/azure/networking/azure-network-latency), the latencies are 80 ms across west and east US regions while < 10 ms in same region.

These latencies are dictated by laws of physics and dictate the minimum RPO we can achieve (although realistically it is going to be orders higher for intermediate checksum, metadata updates roundtrips etc). Some existing example services like [AWS Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-disaster-recovery.html#aurora-global-database-manage-recovery) enforces minimum RPO of 20 seconds.

Since 0 RPO for cross-region workloads is very challenging to achieve realistically, it is a careful conscious decision to choose sync vs async replication mode.

Few things to keep evaluate
1. OpenSearch supports wide variety of usecases from ingestion heavy log-analytics workloads of peta-byte scale through search heavy usecases. Are there thoughts on which workloads should CCR support?
2. Sync replication adds strong coupling on health and performance of remote cluster in addition to network latencies. This might not be desirable for all usecases.
3. One of the arguably needle moving advances happening in OpenSearch is support for remote store ([#1968](https://github.com/opensearch-project/OpenSearch/issues/1968)). The main intent is to achieve high durability via external battle tested object stores. Async approach can support wide variety of configurations including non-remote store as per different usecases.

**Comment by krishna-ggk** [comment]
> RTO can be tricky. What would we consider as RTO? At a basic RTO is the time it takes a system to recover from a failure event. A system should try and minimize the RTO. In which case it is important that
> 
>     1. the mean time to detect failure is low,
> 
>     2. time it takes to start recovery is low,
> 
>     3. the time it takes to reconcile the data is low or data reconciliation should be fast.
> 
> 
> In each of the above case we need to ensure we have the appropriate events, metrics and process.
> 
> Failure Detection - Full cluster failure, node failure, network failure, can all impact the ability to replicate and hence need to be detected fast. It could be a combination of health pings between clusters, latency, replication lag and timeouts.

Totally agree. I'd like to call on attention to the fact that some failure detection will have to be external to detect any cluster level outages. Overall, we need to lay in the requirements/documentation on how one can achieve near 0 RTO based on metrics and APIs exposed by OpenSearch.

From OpenSearch CCR point of view, the APIs to switch role (follower/leader or secondary/primary) and them being reliable and performant would be key.

**Comment by krishna-ggk** [comment]
> We propose relying on an asynchronous replication model where user can define its RPO & RTO requirements.
> Let's assume we're using Segment Replication with Remote Store. We can piggyback on local cluster level durability guarantees to ensure minimal RPO.
> For example, as soon as segments are written to Primary's remote store(with refresh or commit), these changes are always available to the secondary clusters. Incase of Primary outage, secondary can ensure that all the latest segments have been downloaded. As an additional step during failover, we can even explore fetching primary's translog to ensure no data loss. This would ensure we have near-zero RPO & RTO in happy cases.

Nice! Few caveats though

1. The translog itself may be not accessible if the primary cluster is down. If you are refering to remote translog, then perhaps yes.
2. In case of whole environment outage (ex region level in cloud provider environment), the remote store itself should be replicated or the RTO guarantees will have to be explicit about this remote store dependency.

**Comment by krishna-ggk** [comment]
> * One optimisation over this could be to rely on the remote store's capability for cross region replication. With this approach, data from Primary's remote store is replicated directly to the Secondary's remote store and secondary cluster can fetch data directly from its remote store. In this case, if a network partition happens, we can rely on underlying remote store's guarantees(e.g. S3 guarantees 15 mins for 99.99) for ensuring that the data is available to the Secondary clusters.

Ok yes - this speaks to caveat 2 and just that it may also be due to outage of remote store (not just network partition).

**Comment by saikaranam-amazon** [comment]
> As an additional step during failover, we can even explore fetching primary's translog to ensure no data loss. This would ensure we have near-zero RPO & RTO in happy cases.

We should consider replicating remote store translog not just during the failover. As the cluster/remote store might not be avaiable during the failover and this ensures desired RPO is maintained in all the cases. 


> Incase the replication lag is high, we'd also need the necessary tuning parameters which can be leveraged to ensure we meet the Replication lag SLA.

Any tuning params for replication warrants additional resource consumption on leader(and on follower). In most of the cases, this additional load can eat into the resources used for on-going workloads running on the cluster. At leader cluster side, this involves bookkeeping of follower cluster states (as might be replicating at different rates) and allocation of resources to achieve desired RPO. As we are already exploring remote store(on cloud) as an option, we should consider design of replication component external to the clusters that can perform this job without additional overhead on the participating clusters within the replication group.

**Comment by saikaranam-amazon** [comment]
> the time it takes to reconcile the data is low or data reconciliation should be fast.

> Recovery - If we look at a fully managed experience, it should include ability to do a failover in case a primary cluster is impacted. While the failover happens, primary cluster may need to recover. This recovery will require that first it is established that the cluster up and running and it catches back to the current state of data in the group of clusters.


Yes, we will need to optimize on both detection and recovery mechanisms.
For recovery within the replication group, In addtion to data reconcialation across the clusters, this needs additional handling from the plugins side. 
Depending on the role of the cluster within the replciation group - PRIMARY / SECONDARY. Plugin behavrior/actions might have to be on PASSIVE mode and without much overhead should shift to ACTIVE mode after SECONDARY cluster is promoted to primary.

**Comment by ankitkala** [comment]
I agree on the need to optimise detection & recovery mechanism. 


> Any tuning params for replication warrants additional resource consumption on leader(and on follower). In most of the cases, this additional load can eat into the resources used for on-going workloads running on the cluster. At leader cluster side, this involves bookkeeping of follower cluster states (as might be replicating at different rates) and allocation of resources to achieve desired RPO. As we are already exploring remote store(on cloud) as an option, we should consider design of replication component external to the clusters that can perform this job without additional overhead on the participating clusters within the replication group.

What resource  are we talking about in this case? CPU or I/O?  
Irrespective of whether we go with external replication replication component or not, we'll have to do the bookkeeping as well as segments upload on leader.

Here are the pros/cons of using the remote store level replication. Feel free to add if you've got more.
**Pros:** 
- Allows us to achieve better cross-region RPO & RTO guarantees during Failover(incase of region level failures)
- We piggyback on the guarantees provided by remote store for cross region copy.    

**Cons:**
- Will be additional effort. Unless this is the only supported combination.
- We'll be continuously copying leader's remote translog to follower's bucket for failover cases. But this continuous data copy(think cross region) would be redundant and not used during normal operations. 
- With introduction of additional component in data transfer(i.e. follower's remote store), we can potentially have higher replication lag.
