### ISSUE TITLE
CCR move to Core 

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#615]
This issue documents the plan around CCR's move to core (See RFC [here](https://github.com/opensearch-project/OpenSearch/issues/2872)). Some questions that we'll cover here: 
- Tradeoff between CCR as a core component vs CCR as an extension. 
- Plan for shifting to CCR as core feature. 

---

**CCR as core vs CCR as extension:** 
There are also ongoing effort towards building support for [extensions](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/DESIGN.md). We also evaluated whether it makes sense for CCR to evolve as an extension. 
Going forward, Extension would allow you to extend features of OpenSearch which will run in a separate process/node via a new Opensearch SDK. Apart from providing isolation via sandboxed environment, it'll also ensure that plugin owners don't have to build the extension separately for all the versions. Moreover, it will also reduce the coupling between core and the plugin owners as the extensions would only be able to access the classes which are public and supports backwards compatibility. 
Coming back to CCR, we propose CCR as a core feature instead of the extension. CCR as a feature is closely coupled with the OS internals. For example:
- The choice of replication model between primary and replica will decide how CCR should replicate the data. Moreover, for CCR using Segment Replication, it makes sense to reuse the existing implementation of Segment Replication by converging the both towards a common approach.
- With the evolution towards remote store, we would need additional optimisations where follower cluster can directly fetch the data(segments, translogs, cluster state, etc) from leader's remote store to avoid overhead on leader's nodes. 
- With Full cluster replication, we'd have to replicate the data & metadata for all the indices. We might have to build the constructs in core to distinguish what data should be replicated and what shouldn't (e.g. different settings, system indices).
- To support use cases like failover and failback, we'd need to switch the cluster's configuration at runtime. For e.g. making the follower replicate from leader in a passive mode. This might require changing engine's behaviour(disabling/enabling IndexWriter) at runtime.
- Potentially strong synergy with efforts for migration tooling. 

Technically all these issues can be handled with extensions as well but it might be require building very deep extensions which can be difficult to maintain(in terms of backward compatibility). And since CCR is closely trying to evolve with core OS features, it makes more sense to have CCR implemented in core.

---

**Can we move CCR to core right away?**

Nope. We propose not to move CCR in its current state

- CCR has a strong dependency on security plugin and can't move to core unless security plugin is moved to core. With move towards extensions. Security won't move all its existing features to core but instead build authN & authZ with consideration for extensions. We'll need to overhaul the security design on CCR. 
- CCR is a kotlin plugin and moving to core would imply re-writing the complete logic in Java.

The two points mentioned above make sense if we want to keep building on top of the current implementation. However, with Full cluster Replication, we might design components differently considering the other initiatives around Segment Replication, Remote Store and stronger Security model for cross cluster(maybe a handshake based approach instead of the current role based approach). 

Instead of moving to core, we propose rewriting CCR in core directly as full cluster replication. To start with, it can leverage Segment Replication & Remote Store but would be extensible to a logical implementation(if required in future). The current plugin can stay in KTLO and have a plan for eventual deprecation. 

---
**Can we still move some parts of CCR to core right away so that segment replication can re-use those?**

These are the sub-packages in the repository with the details: 

| Package name (org.opensearch.*)| Details | Can be moved to core? | Can be moved to core to be reused for SegRep CCR ? | Notes |
|--------------|---------|---------------|----------------|-------|
|  replication.rest | CCR Rest Handlers | No | N/A |  security roles aware + needs replication metadata    |
|  replication.task | Persistent tasks for managing replication on follower (per index) | No | N/A | manages replication state in the metadata + aware of leader/follower security context |
| replication.action.index | Transport actions to start replication task for an index.  | No | N/A | security roles aware + needs replication metadata |
|  replication.action.update | Transport action for update | No |  N/A |  needs replication metadata |
|  replication.action.stop | Transport action for stop replication | No    |  | needs replication metadata |
|  replication.action.pause | Transport action to pause a replicating index. |     No   | N/A | needs replication metadata |
|  replication.action.resume | Action to resume a replicating index in paused state  |  No |  N/A | needs replication metadata |
|  replication.action.stats | Generates replication stats  | No  |  N/A | needs replication metadata |
|  replication.action.status | Replication state for an index |   No |   N/A  | needs replication metadata |
|  replication.action.replicationstatedetails | Publishes cluster state for replication state update | No | N/A  |  |
| replication.action.changes | Get ops to be replayed from leader. | Maybe | No | Needs to track the metrics for leader_stats. Technically, it can be refactored to move to core but it won't be executed on dedicated replication threadpool. |
|  replication.action.replay | Apply the translog changes to follower cluster.  | Maybe | No | Need to refactor extract out mapping updates on follower index. Also, won't run on replication threadpool |
|  replication.action.repository | Follower index bootstrapping, applies snapshot to follower | Not sure  |  No | Won't be required for Segrep CCR  |
|  replication.repository | Logic for follower index snapshot restore from leader |  Not sure |   No |  Won't be required for Segrep CCR |
|  replication.metadata | Replication state metadata as system index | No |  N/A |  System index for CCR plugin also persists security roles |
|  replication.ReplicationEngine | Engine override on follower index | Yes |   No |  SegRep will use NRTReplicationEngine |
| index.translog | Translog deletion policy for leader index | No | No | Deletion policy was moved from core to CCR |

There are very few packages that we can explore refactoring and moving to core(ReplicationEngine, fetching leader changes, apply changes on follower). But all these won't be applicable to the SegRep CCR implementation in the core.

**Comment by krishna-ggk** [comment]
Thanks for the proposal and overall looks good.

> CCR has a strong dependency on security plugin and can't move to core unless security plugin is moved to core. With move towards extensions. Security won't move all its existing features to core but instead build authN & authZ with consideration for extensions. We'll need to overhaul the security design on CCR.

Let us link the related issues - 
- High level AuthN/Z in Core https://github.com/opensearch-project/OpenSearch/issues/4514
- Identity feature branch with roadmap https://github.com/opensearch-project/OpenSearch/blob/feature/identity/IDENTITY_ROADMAP.md

**Comment by ankitkala** [comment]
> Could you elaborate more what are the key differences between the current CCR implementation and the new proposed full cluster replication?

We'll put up a detailed design proposal for full cluster replication review when we've solidified few of the design choices. But full cluster replication should have few additional features like: 
- ability to start/stop/pause/resume at cluster level.
- replicating system indices(need to work with various plugins)
- replicating cluster level settings & metadata (yet to be decided)
- ability to failover and failback (switch the direction of replication).

> How you are going to rid of the hard security dependency?
We want to build this directly in core so it can only leverage what is available in core. Moreover, currently replication metadata stores the information about leader & follower's roles to assume. We need to work with security to break away from this model. We're still discussing on how this would like. Will keep you posted.
