### ISSUE TITLE
Backport Windows support to 1.x branch

### ISSUE THREAD

**Issue by rishabh6788** [opensearch-project/cross-cluster-replication#634]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/181, backport Windows support to 1.x branch.

- [x] Passing CI for 1.x branch on Windows
- [x] Documentation

If you are already have an issue tracking backport Windows CI to 1.x branch, please link here.

**Comment by saikaranam-amazon** [comment]
@rishabh6788 Are we targeting any release/date for this one?
