### ISSUE TITLE
[BUG] Replication job moves to paused state after old node joins the cluster

### ISSUE THREAD

**Issue by saikaranam-amazon** [opensearch-project/cross-cluster-replication#646]
**What is the bug?**
Replication job moves to paused state after old node joins the cluster

**How can one reproduce the bug?**
1. Trigger persistent tasks and ensure that the tasks are in running state.
2. Identify the node(node1) running the persistent task.
3. Ensure OpenSearch process is still up on the node(node1) but induce any network failure to stop all connections to this node.
4. Wait for the cluster manager to mark the node(node1) as unhealthy and let the persistent task registered in step#1 run on new node(node2).
5. Let the node1 join the cluster again.
6. See that the task is in cancelled state and replication is in paused state.

**What is the expected behavior?**
Replication should continue after node recovery.

**Comment by nisgoel-amazon** [comment]
assign it to me

**Comment by nisgoel-amazon** [comment]
This one is already fixed with this https://github.com/opensearch-project/cross-cluster-replication/pull/1004
