### ISSUE TITLE
[FEATURE] Support CCR for k-NN enabled indices.

### ISSUE THREAD

**Issue by krishna-ggk** [opensearch-project/cross-cluster-replication#650]
**Is your feature request related to a problem?**
CCR isn't supported on kNN-enabled indices currently due to [interoperability issues](https://github.com/opensearch-project/cross-cluster-replication/blob/2.x/src/main/kotlin/org/opensearch/replication/action/index/TransportReplicateIndexAction.kt#L102). Given that k-NN refactored to use extension point, the earlier interoperability issues potentially should no longer exist.

**What solution would you like?**
It appears that CCR plugin no longer need to explicitly block k-NN enabled indices for replication. Post running thorough tests (regular + upgrades), CCR plugin can add back support to replicate k-NN enabled indices.

**Comment by navneet1v** [comment]
Hi @monu-aws 
When we are planning to enable the CCR for K-NN indexes?

**Comment by monu-aws** [comment]
Hi @navneet1v , raised PR here https://github.com/opensearch-project/cross-cluster-replication/pull/760

**Comment by monu-aws** [comment]
Hi @navneet1v , Raised PR here, https://github.com/opensearch-project/cross-cluster-replication/pull/760

**Comment by navneet1v** [comment]
Thanks for the update. I hope this get added in 2.7 release. Can we make sure that we update the documentation also, so that customers are aware of this change.

**Comment by monu-aws** [comment]
Hi @navneet1v, changes were merged after the 2.7 code freeze.
