### ISSUE TITLE
Add auto github release workflow

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/cross-cluster-replication#703]
### Is your feature request related to a problem?
As part of OpenSearch releases, `opensearch-build` pushes a tag for the release commit.
But publishing a github release based on the tag is manual.

### What solution would you like?
We've added this workflow[1] in OpenSearch which publishes github releases automatically when a tag is pushed.

Add this workflow to all repos releasing software in the project.
See example: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/auto-release.yml
Example Release: https://github.com/opensearch-project/OpenSearch/releases/tag/2.5.0

[1] https://github.com/opensearch-project/opensearch-plugins/blob/main/WORKFLOWS.md#auto-github-releases

**Comment by ankitkala** [comment]
I've added the github workflow to the main branch but i don't have a way to verify the changes. We'll verify these during the ongoing 2.6 release

**Comment by ankitkala** [comment]
Hey @saratvemulapalli, this was already fixed in https://github.com/opensearch-project/cross-cluster-replication/pull/726

Are you still seeing this issue?

**Comment by ankitkala** [comment]
I'll close this one since its already fixed. Please open a new one if you're still seeing the issue.
