### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#704]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by ankitkala** [comment]
@dblock Regarding point 3 and 4 above, I don't think i have access for these

**Comment by ankitkala** [comment]
Closing now. Please reopen anything is pending from our side.

**Comment by dblock** [comment]
Permissions are incorrect. Please work with @bbarani's team to remove the group that has maintain rights, and add individuals with maintain access.

![Screenshot 2023-04-20 at 10 27 05 AM](https://user-images.githubusercontent.com/542335/233397160-5702c528-3eac-4840-b554-a8a22a7767e2.png)

**Comment by bbarani** [comment]
Baselined the maintainers and CODEOWNERS is green now. Closing this issue.

**Comment by dblock** [comment]
Verified, thx.
