### ISSUE TITLE
[Testing Confirmation] Confirm current testing requirements

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/cross-cluster-replication#721]
As part of the discussion around implementing an organization-wide testing policy, I am visiting each repo to see what tests they currently perform. I am conducting this work on GitHub so that it is easy to reference. 

Looking at the Cross Cluster Replication repository, it appears there is 

| Repository  | Unit Tests | Integration Tests | Backwards Compatibility Tests | Additional Tests | Link | 
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | 
| Cross Cluster Replication | <li>- [x] </li> | <li>- [x] </li> | <li>- [x] </li> | Certificate or Origin, Security Tests | https://github.com/opensearch-project/cross-cluster-replication/issues/721 | 

I don't see any requirements for code coverage in the testing documentation. If there are any specific requirements could you respond to this issue to let me know? 

If there are any tests I missed or anything you think all repositories in OpenSearch should have for testing please respond to this issue with details.

**Comment by ankitkala** [comment]
We do measure code coverage([here](https://github.com/opensearch-project/cross-cluster-replication#cross-cluster-replication-plugin)) as part of every commit push. There is no enforcement as of now but we do ensure that tests are getting added with each change
