### ISSUE TITLE
Cross-cluster replication question

### ISSUE THREAD

**Issue by loxiaopohaiol** [opensearch-project/cross-cluster-replication#742]
I have one question for the cross-cluster replication, when I use this plugin, I want to write the follower cluster's indices data(which index is auto follow from the leader cluster). And when the leader cluster is broken. Can I do this?

**Comment by monu-aws** [comment]
Hi [loxiaopohaiol](https://github.com/loxiaopohaiol) , I understand that you would like to know if you will be able to write data to the follower index when the leader cluster is broken.

I would like to inform you that when cross cluster replication is set up between two clusters( leader and follower), the index on follower is blocked for write and you can only search that index. Any writes to follower index are blocked when CCR is running.

To allow data to be ingested on follower domain, cross-cluster replication must be stopped, this removes the write block and the index is open for writes.

I hope the above answers your question. Feel free to add any other questions you might have.
