### ISSUE TITLE
[Backport] XContent Refactor to 2.x

### ISSUE THREAD

**Issue by nknize** [opensearch-project/cross-cluster-replication#756]
XContent namespace refactor from common -> core is going to be merged to opensearch/2.x which will break the 2.x build.  This issue is for backporting #718 to 2.x after the core namespace change is merged.

Depends on https://github.com/opensearch-project/OpenSearch/pull/6470

**Comment by ankitkala** [comment]
merged https://github.com/opensearch-project/cross-cluster-replication/pull/761
