### ISSUE TITLE
Pass Exceptions to the Retry method

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/cross-cluster-replication#78]
Currently the `Extensions.suspendExecuteWithRetries` retries for all exceptions which are part of the `TransportActions.isShardNotAvailableException` method. `IndexNotFoundException` is also included in `ShardNotAvailableException` due to which it gets retried. But `IndexNotFoundException` is not a transient exception and should not be retried. So we need a better way to decide which exception to retry for. Either the `retryOn` parameter should always be passed by the caller or a function should be passed to decide whether to this method which will be used to decide whether an exception should be retried.

Reference : https://github.com/opensearch-project/cross-cluster-replication/blob/main/src/main/kotlin/com/amazon/elasticsearch/replication/util/Extensions.kt#L114

**Comment by saikaranam-amazon** [comment]
Pushed as part of 1.1 release.
