### ISSUE TITLE
[BUG]Leader checkpoint is not updated in case shard replication task reinitiate

### ISSUE THREAD

**Issue by nisgoel-amazon** [opensearch-project/cross-cluster-replication#900]
**What is the bug?**
We have seen in follower stats API, follower checkpoint is much ahead of leader checkpoint when shard replication task is reinitialized and there are no changes happening on that particular index.

**How can one reproduce the bug?**
1. Create Leader index and start the replication on follower domain
2. Add data on leader index and get it synced on follower domain
3. Bounce OpenSearch on one of the data node on which shard replication task is working
4. Check follower_stats API, It should have follower_checkpoint greater than leader_checkpoint

**What is the expected behavior?**
follower_stats API should return correct data

**What is your host/environment?**
 - OS: linux
 - Version OS_2.7
 - Plugins CCR

**Comment by monusingh-1** [comment]
Closing
