### ISSUE TITLE
[BUG]Stop replication API should clear persistent tasks from cluster state

### ISSUE THREAD

**Issue by nisgoel-amazon** [opensearch-project/cross-cluster-replication#903]
**What is the bug?**
If we have stuck tasks in cluster state, those should be cleared via stop replication API

**How can one reproduce the bug?**
1. Start Replication between follower and Leader domain
2. Induce some stale cluster task entries in cluster state
3. Try to stop and start replication, always get error for `ResourceAlreadyExistsException `

**What is the expected behavior?**
Stop API should be able to clear any persistent task from cluster state

**What is your host/environment?**
 - OS: linux
 - Version: OS_2.7
 - Plugins: CCR

**Comment by monusingh-1** [comment]
Resolved in #905
