### ISSUE TITLE
Add copyright to README and remove year from NOTICE

### ISSUE THREAD

**Issue by dblock** [opensearch-project/cross-cluster-replication#96]
See https://github.com/opensearch-project/.github/issues/21

**Comment by krishna-ggk** [comment]
Noting example - https://github.com/opensearch-project/.github/pull/24/files

**Comment by soosinha** [comment]
@dblock The plugin itself does not contain Elastic code. But it depends on OpenSearch libraries which has Elastic code. So is it fine to remove the Elastic copyright from NOTICE ?
